name: Tutorial
version: 1.0
author: TeddyRNA
main: com.teddyrna.tutorial.Tutorial
api-version: 1.14
commands:
  heal:
    description: Heals player to max health
    usage: /<command>
    aliases: [healing, healme, healmax]
  feed:
    description: Feeds player to max saturation
    usage: /<command>
    aliases: feedme
  spawnmob:
    description: Spawns a specified mob
    usage: /<command>
  givewand:
    description: gives wand to player
    usage: /<command>
  select:
    description: select menu
    usage: /<command>

